version: 2.1
jobs:
  #only one job to create infrastructure; created a user on AWS Console.
  create_infrastructure:
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run: 
            name: Create Cloudformation Stack 
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1
  # Exercise: Config and Deployment
  configure_infrastructure: 
     docker:
       - image: python:3.7-alpine3.11
     steps:
       - checkout
       - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["64:8a:29:b0:2a:bc:22:dc:10:55:d5:91:b6:3b:fc:37"] 
       - run:
           name: Install Ansible
           command: |
             apk add --update ansible

       - run:
           name: Run Playbook and Configure server
           command: |
             ansible-playbook -i inventory main.yml
            
# Sequential workflow
workflows:
  # Name the workflow
  my_workflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure
